apiVersion: apps/v1
kind: Deployment
metadata:
  name:  dotnet-test-app
  namespace: ${TEST_NS}
  labels:
    app: test-app-dotnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app-dotnet
  template:
    metadata:
      labels:
        app: test-app-dotnet
    spec:
      containers:
      - name: test-app-dotnet
        image: ${DOTNET_TEST_IMAGE_NAME}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: test-app-dotnet-service
  namespace: ${TEST_NS}
  labels:
    app: test-app-dotnet
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: test-app-dotnet