apiVersion: azmon.app.monitoring/v1
kind: AppMonitoringConfig
metadata:
 name: appmonitoring
 namespace: "<app-k8s-namespace>"
spec:
 aiConnectionString: "<applicationInsightsConnectionString>"
 autoInstrumentation: "<AzureNative | OTELNative | None>" # optional, default AzureNative
 appMonitoringScope: [ "<deployment1>", "<deployment2>" , "<deploymentN>"]   # optional, specify list deployments to target app monitoring
