kind: ConfigMap
apiVersion: v1
data:
  prometheus-config: |-
    scrape_configs:
    - job_name: ama-logs-fluentbit
      kubernetes_sd_configs:
        - role: pod
      relabel_configs:
        - source_labels: [__meta_kubernetes_pod_controller_kind]
          action: keep
          regex: 'DaemonSet'
        - source_labels: [__meta_kubernetes_pod_controller_name]
          regex: 'ama-logs'
          action: keep
        - source_labels: [__meta_kubernetes_pod_container_port_number]
          regex: '9102'
          action: keep
metadata:
  name: ama-metrics-prometheus-config
  namespace: kube-system