jobs:
    - job: test
      variables:
        armServiceConnectionName: 'ci-1es-acr-connection'
        subscription: '9b96ebbd-c57a-42d1-bbe9-b69296e4c7fb'
      pool:
        name: Azure-Pipelines-CI-Test-EO
      steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: '${{ variables.armServiceConnectionName }}'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az --version
                az account show
                az account set -s ${{ variables.subscription }}
                
                # Define the resource group and AKS cluster name
                resourceGroup="ci-logs-prod-aks"
                aksClusterName="daily_enable_disable_test"
                
                # Check if the omsagent addon is enabled
                addonEnabled=$(az aks show --resource-group $resourceGroup --name $aksClusterName --query addonProfiles.omsagent.enabled -o tsv)
                
                if [ "$addonEnabled" == "true" ]; then
                    echo "OMSAgent addon is enabled on the AKS cluster."
                    az aks disable-addons --addons monitoring --name $aksClusterName --resource-group $resourceGroup
                    sleep 10
                    echo "Re-enabling the OMSAgent addon..."
                    az aks enable-addons --addons monitoring --name $aksClusterName --resource-group $resourceGroup
                    echo "OMSAgent addon has been re-enabled."
                else
                    echo "OMSAgent addon is not enabled on the AKS cluster."
                fi