jobs:
    - job: test
      variables:
        armServiceConnectionName: 'ci-1es-acr-connection'
        subscription: '9b96ebbd-c57a-42d1-bbe9-b69296e4c7fb'
      pool:
        name: Azure-Pipelines-CI-Test-EO
      steps:
          - task: AzureCLI@2
            inputs:
                azureSubscription: ${{ variables.armServiceConnectionName }}
                scriptType: 'bash'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  az --version
                  az account show
                  az account set -s ${{ variables.subscription }}
                  az aks addon show --addon monitoring --name daily_enable_disable_test --resource-group ci-logs-prod-aks