jobs:
    - job: test
      variables:
        armServiceConnectionName: 'ci-1es-acr-connection'
      steps:
          - task: AzureCLI@2
            inputs:
                azureSubscription: ${{ variables.armServiceConnectionName }}
                scriptType: 'bash'
                scriptLocation: 'inlineScript'
                inlineScript: 'az aks list --resource-group ci-logs-prod-aks'