jobs:
    - job: test
      steps:
          - task: AzureCLI@2
            inputs:
                azureSubscription: 'ContainerInsights_Build_Subscription(9b96ebbd-c57a-42d1-bbe9-b69296e4c7fb)'
                scriptType: 'bash'
                scriptLocation: 'inlineScript'
                inlineScript: 'az aks list --resource-group ci-logs-prod-aks'