on:
  release:
    types:
      - created
    tags:
      - '*-appmonitoring'

variables:
  armServiceConnectionName: 'ci-1es-acr-connection'
  testSubscriptionId: test-sub
  testRG: rgg
  testClusterName: test-cluster
  subscription: '9b96ebbd-c57a-42d1-bbe9-b69296e4c7fb'
  containerRegistry: 'containerinsightsprod' # this build pushes the aidev image to the dev ACR (caution: ACR that has "prod" in its name is the dev one, the one without "prod" is prod AME)
  repoImageName: '${{ variables.containerRegistry }}.azurecr.io/public/azuremonitor/applicationinsights/aidevtest'
  IS_PR: $[eq(variables['Build.Reason'], 'PullRequest')]

stages:
- stage: Test
  jobs:
  - job: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Create AKS Cluster
      displayName: "Deploy to AKS and test results"
      inputs:
        azureSubscription: ${{ variables.testSubscriptionId }}
        azureRG: ${{ variables.testRG }}
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: | 
          asdadas

    - name: Validate image
      displayName: "Install AKS resources and validate image funtionality"
      inputs: 
        adasdasd: asfasfas
        inlineScript: |
          asdasdasdasdasd

    


- stage: Deploy
  jobs:
  - job: Deploy
    steps:
    - script: echo Deploying the project...
      displayName: 'Deploy'
